project:
  type: website
  output-dir: docs

website:
  title: "Yu, Lexun"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true